services:
    api:
        container_name: 'workshop_api'
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
